### ISSUE TITLE
BestPractice-Authorization.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#1]
- Markdown 文件：[BestPractice-Authorization.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/learn/BestPractice-Authorization.md)
- PR 地址：#42

---

- 翻译时间：`2` 天
- 校对时间：`1` 天
- 翻译积分：`2` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ydfzgyj** [comment]
搬迁翻译完毕，请审校
