### ISSUE TITLE
Learn-Queries.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#10]
- Markdown 文件：[Learn-Queries.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/learn/Learn-Queries.md)
- PR 地址：#37

---

- 翻译时间：`14` 天
- 校对时间：`4` 天
- 翻译积分：`7` 分
- 校对积分：`2` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jonirrings** [comment]
我们这边翻译已完成，有劳校对

**Comment by whisperfairy** [comment]
申请校对2017/8/2 -2017/8/5

**Comment by linhe0x0** [comment]
@whisperfairy 好哒
