### ISSUE TITLE
官网无法打开

### ISSUE THREAD

**Issue by vcjmhg** [xitu/graphql.github.io#105]
您好，https://graphql.cn 网站好像无法打开
![image](https://user-images.githubusercontent.com/55177318/102004924-273e3b80-3d50-11eb-8270-b536982d1eba.png)

**Comment by jonirrings** [comment]
因为是直接用的github pages，所以有时候会因为防火墙问题抽风。

**Comment by vcjmhg** [comment]
好的，谢谢！
