### ISSUE TITLE
Learn-Schema.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#11]
- Markdown 文件：[Learn-Schema.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/learn/Learn-Schema.md)
- PR 地址：#38

---

- 翻译时间：`12` 天
- 校对时间：`2` 天
- 翻译积分：`6` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by AceLeeWinnie** [comment]
@sqrthree 认领

**Comment by linhe0x0** [comment]
好的

**Comment by jonirrings** [comment]
我们这边翻译已完成，有劳校对

**Comment by linhe0x0** [comment]
@AceLeeWinnie PR 地址已更新，为了避免重复劳动，就不用翻译了哈。详情微信上已沟通过。感兴趣的话可以参与校对啦~~
