### ISSUE TITLE
APIReference-Errors.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#13]
- Markdown 文件：[APIReference-Errors.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/graphql-js/APIReference-Errors.md)
- PR 地址：#52

---

- 翻译时间：`2` 天
- 校对时间：`1` 天
- 翻译积分：`1` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
翻译认领

**Comment by linhe0x0** [comment]
好哒
