### ISSUE TITLE
APIReference-ExpressGraphQL.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#15]
- Markdown 文件：[APIReference-ExpressGraphQL.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/graphql-js/APIReference-ExpressGraphQL.md)
- PR 地址：

---

- 翻译时间：`稍后添加` 天
- 校对时间：`稍后添加` 天
- 翻译积分：`稍后添加` 分
- 校对积分：`稍后添加` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by XatMassacrE** [comment]
翻译认领

**Comment by linhe0x0** [comment]
好的
