### ISSUE TITLE
APIReference-GraphQL.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#16]
- Markdown 文件：[APIReference-GraphQL.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/graphql-js/APIReference-GraphQL.md)
- PR 地址：#59

---

- 翻译时间：`4` 天
- 校对时间：`2` 天
- 翻译积分：`2` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by 0x0042** [comment]
我来，这个和在翻译计划一样的流程么，fork然后建新分支提PR？

**Comment by 0x0042** [comment]
看了公告，明白了

**Comment by linhe0x0** [comment]
好哒
