### ISSUE TITLE
APIReference-Language.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#17]
- Markdown 文件：[APIReference-Language.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/graphql-js/APIReference-Language.md)
- PR 地址：#73

---

- 翻译时间：`6` 天
- 校对时间：`2` 天
- 翻译积分：`3` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by 0x0042** [comment]
这个我也要了

**Comment by linhe0x0** [comment]
OK
