### ISSUE TITLE
APIReference-TypeSystem.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#18]
- Markdown 文件：[APIReference-TypeSystem.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/graphql-js/APIReference-TypeSystem.md)
- PR 地址：#61

---

- 翻译时间：`4` 天
- 校对时间：`2` 天
- 翻译积分：`2` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hikerpig** [comment]
认领翻译

**Comment by linhe0x0** [comment]
好哒
