### ISSUE TITLE
APIReference-Validation.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#20]
- Markdown 文件：[APIReference-Validation.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/graphql-js/APIReference-Validation.md)
- PR 地址：#68

---

- 翻译时间：`4` 天
- 校对时间：`2` 天
- 翻译积分：`2` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jonirrings** [comment]
此章节由我翻译，翻译时间为 2017.08.7-2017.08.9。
