### ISSUE TITLE
Tutorial-BasicTypes.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#23]
- Markdown 文件：[Tutorial-BasicTypes.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/graphql-js/Tutorial-BasicTypes.md)
- PR 地址：#63

---

- 翻译时间：`4` 天
- 校对时间：`2` 天
- 翻译积分：`2` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jonirrings** [comment]
此章节由我翻译，翻译时间为 2017.08.5-2017.08.6。
