### ISSUE TITLE
Tutorial-ExpressGraphQL.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#24]
- Markdown 文件：[Tutorial-ExpressGraphQL.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/graphql-js/Tutorial-ExpressGraphQL.md)
- PR 地址：#48

---

- 翻译时间：`4` 天
- 校对时间：`2` 天
- 翻译积分：`2` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by hikerpig** [comment]
认领翻译, 预计 7.27 - 8.1

**Comment by linhe0x0** [comment]
OK
