### ISSUE TITLE
Tutorial-GettingStarted.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#25]
- Markdown 文件：[Tutorial-GettingStarted.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/graphql-js/Tutorial-GettingStarted.md)
- PR 地址：#53

---

- 翻译时间：`4` 天
- 校对时间：`2` 天
- 翻译积分：`2` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tina92** [comment]
@sqrthree 翻译认领

**Comment by linhe0x0** [comment]
好哒
