### ISSUE TITLE
Tutorial-ObjectTypes.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#28]
- Markdown 文件：[Tutorial-ObjectTypes.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/graphql-js/Tutorial-ObjectTypes.md)
- PR 地址：#74

---

- 翻译时间：`4` 天
- 校对时间：`2` 天
- 翻译积分：`2` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by dabanlee** [comment]
此章节由我翻译，翻译时间为 2017.08.5-2017.08.8。

**Comment by linhe0x0** [comment]
好哒
