### ISSUE TITLE
Tutorial-PassingArguments.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#29]
- Markdown 文件：[Tutorial-PassingArguments.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/graphql-js/Tutorial-PassingArguments.md)
- PR 地址：#51

---

- 翻译时间：`4` 天
- 校对时间：`2` 天
- 翻译积分：`2` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Joursion** [comment]
认领翻译

**Comment by linhe0x0** [comment]
@Joursion 好哒
