### ISSUE TITLE
BestPractice-Introduction.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#3]
- Markdown 文件：[BestPractice-Introduction.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/learn/BestPractice-Introduction.md)
- PR 地址：#44

---

- 翻译时间：`6` 天
- 校对时间：`2` 天
- 翻译积分：`3` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tina92** [comment]
@sqrthree 翻译认领

**Comment by linhe0x0** [comment]
@Tina92 好哒

**Comment by ydfzgyj** [comment]
搬迁翻译完毕，请审校
