### ISSUE TITLE
Community-Resources.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#31]
- Markdown 文件：[Community-Resources.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/community/Community-Resources.md)
- PR 地址：#64

---

- 翻译时间：`6` 天
- 校对时间：`2` 天
- 翻译积分：`3` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ydfzgyj** [comment]
认领这两篇没技术含量的😂

**Comment by linhe0x0** [comment]
Sure
