### ISSUE TITLE
BestPractice-Pagination.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#4]
- Markdown 文件：[BestPractice-Pagination.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/learn/BestPractice-Pagination.md)
- PR 地址：#45

---

- 翻译时间：`6` 天
- 校对时间：`2` 天
- 翻译积分：`3` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ydfzgyj** [comment]
搬迁翻译完毕，请审校
