### ISSUE TITLE
BestPractice-ServingOverHTTP.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#5]
- Markdown 文件：[BestPractice-ServingOverHTTP.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/learn/BestPractice-ServingOverHTTP.md)
- PR 地址：#49

---

- 翻译时间：`4` 天
- 校对时间：`2` 天
- 翻译积分：`2` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by ydfzgyj** [comment]
认领翻译
