### ISSUE TITLE
BestPractice-ThinkingInGraphs.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#6]
- Markdown 文件：[BestPractice-ThinkingInGraphs.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/learn/BestPractice-ThinkingInGraphs.md)
- PR 地址：#33

---

- 翻译时间：`4` 天
- 校对时间：`2` 天
- 翻译积分：`2` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tina92** [comment]
@sqrthree 认领翻译

**Comment by linhe0x0** [comment]
好哒

**Comment by linonetwo** [comment]
我来校对啦

**Comment by linhe0x0** [comment]
@linonetwo  好哒
