### ISSUE TITLE
译者注的格式问题

### ISSUE THREAD

**Issue by ydfzgyj** [xitu/graphql.github.io#62]
今天看到有几篇翻译都出现了译者注，用的方式是`正文（译者注：XX）`的方式
在 [译文排版规则指北](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E5%A6%82%E6%9E%9C%E6%96%87%E7%AB%A0%E4%B8%AD%E6%9C%89%E8%84%9A%E6%B3%A8%E6%80%8E%E4%B9%88%E5%8A%9E) 中又有一种写脚注的方式
我们应该采用哪种？

另外，由于我们最后的成果还需要放在网站上展示，而网站使用的 Markdown 解析器**不支持**把 HTML 标签嵌套在 Markdown 段落中作为行内元素使用
因此如果采用脚注模式，需要修改一些代码以支持 `<sup></sup>` 和 `<a name="xxx">`（已试验过可行）

@sqrthree @jonirrings @linonetwo

**Comment by linhe0x0** [comment]
我觉得 `正文（译者注：XX）` 这种方式更合适一点。

『译文排版规则指北 』指南中的脚注一般多用于标示数据源、名词来源等信息。我觉得我们的『译者注』一般是为了读者更好的理解做出的必要性解释，放在句中看着更直接、明显。

**Comment by jonirrings** [comment]
我也是倾向于`正文（译者案：blablabla）`的格式。对于一整段的注释再用脚注吧？

**Comment by ydfzgyj** [comment]
那像 [这里](https://github.com/xitu/graphql.github.io/pull/42/files#diff-15262d8937d61c955cef3d97074f5e6fR58) 或者 [这里](https://github.com/xitu/graphql.github.io/pull/59/files#diff-b920dde948850971cb134be31e477bdcR24) 一样的名词解释性质的呢？

**Comment by jonirrings** [comment]
短的名词解析就用 `译者案` 方式吧，长的一大段那种就用脚注，自行判断适合哪一种。
当然全用脚注我感觉正式点。

**Comment by ydfzgyj** [comment]
> 短的名词解析就用 译者案 方式吧

那你的“译者案”跟别人的“译者注”也统一一下吧 @jonirrings

**Comment by jonirrings** [comment]
:nerd_face:，嗯嗯

**Comment by ydfzgyj** [comment]
那么脚注既然还是必要的，我开个 PR 改一下 Markdown 解析的代码，然后就麻烦你把使用说明贴到 Wiki 里去喽 @jonirrings

**Comment by jonirrings** [comment]
嗯嗯，你PR嘛。

**Comment by jonirrings** [comment]
已添加到wiki
