### ISSUE TITLE
关于几个category的翻译统一

### ISSUE THREAD

**Issue by jonirrings** [xitu/graphql.github.io#65]
首先抛个砖：

| 英文 | 中文 |
| ---- | ----- |
| LEARN | 学习 |
| BEST PRACTICES | 最佳实践 |
| GRAPHQL.JS TUTORIAL | GRAPHQL.JS 教程 |
| ADVANCED GUIDES | 高级指南 |
| API REFERENCE | API 参考 |

大家来讨论讨论，其他翻译有差异的词语也放在一起讨论吧，譬 validator 究竟是`验证器`，还是`校验器`？

**Comment by jonirrings** [comment]
validator，个人意见是验证器。
我个人的常用情况
校验是用于checksum，对应的动词是verify
验证是用于可行性，对应的动词是validate

@hikerpig 
@ydfzgyj

**Comment by 0x0042** [comment]
`lex` 和 `lexer` 是否统一翻译为 **词法分析** 和 **词法分析器**？

**Comment by jonirrings** [comment]
`lex `和 `lexical analysis` 区分不？区分的话，前者翻译作 **分析词法**，后者 **词法分析**。不区分都翻译作 **词法分析**。
`lexer` 翻译作 **词法分析器** 无异议。

**Comment by ydfzgyj** [comment]
> validator，个人意见是验证器。

“验证器”+1，但是中文里“验证”和“校验”应该没有区别，只是“校验”感觉上比较少用而已
实际上 verify 翻译成“验证”应该更常见，比如：验证码 verification code

**Comment by ydfzgyj** [comment]
> lex 和 lexer 是否统一翻译为 词法分析 和 词法分析器？

赞同

**Comment by hikerpig** [comment]
`validator` “验证器” +1。 考虑到 checksum 这个的话，的确还是不要用 “校验器” 会比较好。

同时问一下，category 和 sublinks 这些是个人在个人的文章里翻译，还是等到文章差不多以后统一翻译替换下？

**Comment by 0x0042** [comment]
个人建议 `lex` 和 `lexical analysis` 都译作 **词法分析**，不作区分。

**Comment by jonirrings** [comment]
> 同时问一下，category 和 sublinks 这些是个人在个人的文章里翻译，还是等到文章差不多以后统一翻译替换下？

@hikerpig 这儿讨论完就统一了，哈哈哈，现在就是统一翻译的时候。我上面给出了砖，麻烦你们出个玉。
@llp0574 嗯嗯，那就不区分。
