### ISSUE TITLE
Introduction.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#7]
- Markdown 文件：[Introduction.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/learn/Introduction.md)
- PR 地址：#36

---

- 翻译时间：`稍后添加` 天
- 校对时间：`稍后添加` 天
- 翻译积分：`稍后添加` 分
- 校对积分：`稍后添加` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Tina92** [comment]
@sqrthree 认领翻译

**Comment by linhe0x0** [comment]
哈哈哈，你得换一篇了，这篇 NIGHT+ 已经在翻译了。抱歉

**Comment by wenqingyu** [comment]
@Tina92 这一篇我们之前大部分翻译过了，稍后可以帮我们校对，谢谢！

**Comment by wenqingyu** [comment]
@sqrthree 确认认领

**Comment by linhe0x0** [comment]
@wenqingyu 好哒

**Comment by jonirrings** [comment]
已翻译完毕，有劳审校

**Comment by linhe0x0** [comment]
这篇好像 NIGHT+ 的小伙伴也翻译完了。

**Comment by linhe0x0** [comment]
PR 地址：#36

**Comment by Tina92** [comment]
@sqrthree 校对认领

**Comment by linhe0x0** [comment]
@Tina92 好哒~
