### ISSUE TITLE
Learn-Execution.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#8]
- Markdown 文件：[Learn-Execution.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/learn/Learn-Execution.md)
- PR 地址：#55

---

- 翻译时间：`8` 天
- 校对时间：`2` 天
- 翻译积分：`4` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by whisperfairy** [comment]
此章节由我翻译，翻译时间为 2017.07.25-2017.08.1。迁移重新认领

**Comment by whisperfairy** [comment]
翻译完成请校对https://github.com/xitu/graphql.github.io/pull/55/files
