### ISSUE TITLE
Learn-Introspection.md

### ISSUE THREAD

**Issue by linhe0x0** [xitu/graphql.github.io#9]
- Markdown 文件：[Learn-Introspection.md](https://github.com/xitu/graphql.github.io/blob/zh-Hans/site/learn/Learn-Introspection.md)
- PR 地址： #54

---

- 翻译时间：`4` 天
- 校对时间：`2` 天
- 翻译积分：`2` 分
- 校对积分：`1` 分
- [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by linonetwo** [comment]
此章节由我翻译，翻译时间为 2017.07.25-2017.08.1。迁移重新认领
